language: node_js
node_js:
  - 6
script:
  - make test-travis
before_script:
  - sudo apt-get install bc
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
notifications:
  email: false
